#%RAML 1.0 Library
 
traits:
  my-common-header: !include mytraits/mytraits-common-headers.raml

  my-common-error: !include mytraits/my-common-error-responses.raml

types:
  get-response: !include My-datatypes/Get_response.raml
 
  post-request: !include My-datatypes/Post_request.raml

  post-response: !include My-datatypes/Post_response.raml

  userDetails: !include My-datatypes/userdetails.raml

  assessmentdetails: !include My-datatypes/Assesmentdetails.raml

  submitionDateTime: !include My-datatypes/submitionDateTime.raml

 

 