#%RAML 1.0 Trait
headers:
      x-fms-transactionId:
        required: true
        type: string
        minLength: 36
        maxLength: 36
        example: "hdsfhjdh-jxbv859-sjdf7643-3746b555bd"
      x-fms-clientId:
        required: true
        type: string
        example: "hsdfgysdhfcdshf37er6twgsdhfjcd"
      x-fms-clientSecret:
        required: true
        type: string
        example: " dsgfhaegur457r6ewsewegrfjesh"